version: "3.8"

services:
  postgress:
    container_name: "nest-dotap-users"
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-dotap
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
